/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f0xx.h"
#include "I2c.h"
#include "VL53L0X.h"

struct VL53L0X myTOFsensor = {.io_2v8 = true, .address = 0b0101001, .io_timeout = 500, .did_timeout = false};
uint8_t readVl53l0x;

void OS_vClockConfiguration(void);
void OS_vTimerConfig(void);

int main(void)
{
	uint16_t valueVl53l0x = 0u;
	readVl53l0x = 0u;
	OS_vClockConfiguration();
	OS_vTimerConfig();
	I2c_vInit();
	delay_vInit();

	VL53L0X_init(&myTOFsensor);
	VL53L0X_setMeasurementTimingBudget(&myTOFsensor, 200000);

	while(1)
	{
		/* read distance in mm every second*/
		if(readVl53l0x == 1u)
		{
			valueVl53l0x = VL53L0X_readRangeSingleMillimeters(&myTOFsensor);
			readVl53l0x = 0u;
		}
	}
}

void OS_vClockConfiguration(void)
{
	/* Configure clock @32MHz*/
	RCC->CFGR = RCC_CFGR_PLLMUL8;								/* Set PLL multiplication factor to 8 	*/
																/* Set PLL input clock source to HSI/2 	*/
																/* Select system clock source to PLL 	*/
	RCC->CR = RCC_CR_PLLON;										/* Enable PLLCLK 						*/
	while((RCC->CR & RCC_CR_PLLRDY) == 0);	    				/* Wait until PLLCLK  is ready 			*/

	RCC->CFGR |= RCC_CFGR_SW_PLL; 								/* Select PLL as system clock 			*/
	while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL); 	/* Wait until the PLL is switched on 	*/

	RCC->APB2ENR = RCC_APB2ENR_DBGMCUEN|RCC_APB2ENR_TIM16EN;	/* Enable MCU debug mode 				*/
																/* Enable TIM16 OS clock 				*/
	RCC->APB1ENR = RCC_APB1ENR_PWREN;							/* Set the Power Enable  				*/
}

void OS_vTimerConfig(void)
{
	TIM16->EGR = TIM_EGR_UG;									/* Reset/update of TIM16				*/

	/* Set timer's period to 1sec @32MHz		*/
	TIM16->PSC = 999;											/* Prescaler							*/
	TIM16->ARR = 32000;											/* auto-reload							*/
	TIM16->DIER = TIM_DIER_UIE;									/* Enable interrupt						*/
	TIM16->CR1 = TIM_CR1_CEN;									/* Enable timer							*/

	NVIC_EnableIRQ(TIM16_IRQn);									/* Enable interruption for TIM16		*/
}

void TIM16_IRQHandler(void)
{
	/* if UIF flag is set */
	if(TIM16->SR & TIM_SR_UIF)
	{
		/* clear UIF flag */
		TIM16->SR &= ~TIM_SR_UIF;
		readVl53l0x = 1u;
	}
}
